export const profile = {
  name: "Yohan Senadheera",
  headline: "Computer Engineering Undergraduate",
  tagline: "Networking • Private 5G • DevOps • Edge",
  location: "Colombo, Sri Lanka",
  university: "University of Peradeniya",
  website: "yohan-senadheera.pages.dev",
  email: "yohansenadheera@gmail.com",
  phone: ["+94 76 802 2347", "+94 72 579 2197"],
  linkedin: "https://linkedin.com/in/yohan-senadheera",
  github: "https://github.com/yohan-senadheera",
  cvUrl: "/Yohan_Senadheera_CV.pdf",

  summary: `Computer Engineering undergraduate with hands-on experience in 5G network deployment, containerization, and cloud infrastructure. Implemented edge UPF on Raspberry Pi, built CI/CD pipelines for containerized network functions on Kubernetes/AWS, and developed mobile applications with Firebase/AWS backends. Seeking DevOps, Software Engineering, or Networking internships that bridge infrastructure, automation, and development.`,

  about: {
    whatIBuild: [
      "Network systems and 5G infrastructure prototypes",
      "Cloud-native deployments with Kubernetes & AWS",
      "Edge computing solutions on embedded hardware",
    ],
    whatICareAbout: [
      "Reliability & high availability",
      "Automation & infrastructure as code",
      "Performance optimization & observability",
    ],
    strengths: [
      {
        title: "Networking",
        description: "Deep understanding of TCP/IP, SDN, 5G core, and network security",
      },
      {
        title: "Cloud-Native",
        description: "Production experience with Docker, Kubernetes, CI/CD, and AWS services",
      },
      {
        title: "Fast Learner",
        description: "Quickly adapt to new technologies and thrive in collaborative environments",
      },
    ],
  },

  projects: [
    {
      title: "Cloud Reliability Platform",
      subtitle: "Infrastructure Monitoring & Reliability",
      type: "Individual Project",
      timeframe: "Feb 2026 – Present",
      description: "Cloud-native reliability platform with real-time monitoring, automated incident response, and comprehensive observability for distributed systems. Provides multi-cloud support with predictive analytics and SLA tracking.",
      tech: ["Kubernetes", "Prometheus", "Grafana", "Docker", "AWS", "Terraform", "CI/CD"],
      whatIDid: "Designed and implemented end-to-end reliability platform with monitoring dashboards, automated alerting, and infrastructure as code deployment",
      result: "Production-ready platform ensuring 99.9% uptime with automated incident detection and response",
      links: {},
      featured: true,
    },
    {
      title: "Private 5G Network Implementation",
      subtitle: "Collaboration with SLTMobitel",
      type: "Group Project",
      timeframe: "Aug 2025 – Present",
      description: "Implementing edge UPF on Raspberry Pi to optimize 5G user-plane traffic. Team manages RAN virtualization and core server optimization for small-scale deployment.",
      tech: ["Raspberry Pi", "Kubernetes", "SDN", "Open vSwitch", "Wireshark", "tcpdump"],
      whatIDid: "Deployed edge UPF on Raspberry Pi, configured SDN networking with Open vSwitch, performed traffic analysis with Wireshark/tcpdump",
      result: "Ongoing industry collaboration with major telecom provider",
      links: {},
      featured: true,
    },
    {
      title: "Mini 5G Edge Network Testbed",
      subtitle: "Cloud-Native Deployment",
      type: "Individual Project",
      timeframe: "Jan 2026 – Present",
      description: "Mini 5G edge network testbed with containerized network functions, automated CI/CD deployment, and real-time network monitoring dashboard.",
      tech: ["Kubernetes", "AWS", "Docker", "CI/CD", "Monitoring"],
      whatIDid: "Designed and implemented entire cloud-native architecture with automated deployment pipelines",
      result: "Fully automated 5G testbed environment",
      links: {},
      featured: true,
    },
    {
      title: "P-E-BO Desk Companion",
      subtitle: "Third Year Project",
      type: "Group Project",
      timeframe: "Dec 2024 – Jul 2025",
      description: "AI desk companion with 7-emotion detection (95% accuracy) and Gemini AI voice interaction. Teammates handled hardware, Raspberry Pi, and 3D printing.",
      tech: ["React Native", "Firebase", "AWS", "Gemini AI", "IoT"],
      whatIDid: "Developed React Native mobile app, Firebase backend integration, AWS deployment, and project website",
      result: "IESL UIY Top 10, Techno 2025 Exhibit, 3rd Place at ICIIS 2025 / I-To-I",
      links: {},
      featured: true,
    },
    {
      title: "MONA Dashboard",
      subtitle: "Second Year Project",
      type: "Group Project",
      timeframe: "Apr 2024 – Oct 2024",
      description: "Production rate tracking dashboard enabling real-time machine monitoring, bottleneck detection, and process optimization.",
      tech: ["MongoDB", "JavaScript", "React.js", "Python", "SCSS", "GitHub"],
      whatIDid: "Developed production rate tracking page with real-time monitoring and bottleneck detection",
      result: "Successfully deployed for manufacturing process optimization",
      links: {},
      featured: false,
    },
    {
      title: "Personalized AI Feedback for Higher Education",
      subtitle: "Final Year Project",
      type: "Group Project",
      timeframe: "Aug 2024 – Present",
      description: "Personalized adaptive learning system with virtual teaching assistant. Team handles data processing, model training, and LMS integration.",
      tech: ["Python", "Node.js", "GPT-3.5", "Moodle"],
      whatIDid: "Implemented AI modules and virtual teaching assistant integration",
      result: "Ongoing development with university LMS integration",
      links: {},
      featured: false,
    },
    {
      title: "Smart Home Energy Automation",
      subtitle: "Mobile Application",
      type: "Group Project",
      timeframe: "Feb 2025 – Apr 2025",
      description: "React Native app for smart home project with Firebase real-time sync, alerts, and remote control capabilities.",
      tech: ["React Native", "Expo", "Firebase", "IoT", "ESP32", "Arduino"],
      whatIDid: "Developed complete mobile application with real-time sync and control features",
      result: "Fully functional smart home control system",
      links: {},
      featured: false,
    },
  ],

  skills: {
    "DevOps & Cloud": ["Docker", "Kubernetes", "AWS", "CI/CD", "Git", "Bash"],
    "Networking": ["TCP/IP", "VLANs", "Switching", "Routing", "SDN", "5G", "Network Security", "Wireshark", "STP", "EtherChannel"],
    "Programming": ["Python", "JavaScript", "React", "React Native"],
    "Databases & Tools": ["SQL", "Firebase", "MongoDB", "Linux Administration"],
  },

  currentlyLearning: ["CCNA 1 & 2", "Kubernetes Advanced"],

  experience: [
    {
      title: "Casual Instructor",
      subtitle: "Database Systems / Programming Methodology",
      organization: "Dept. of Computer Engineering, University of Peradeniya",
      timeframe: "Nov 2024 – Aug 2025",
      description: "Taught 40+ students database systems and C programming through lab sessions and mentoring.",
      type: "teaching",
    },
    {
      title: "Team Captain",
      organization: "Shooting Sports Association, University of Peradeniya",
      timeframe: "Jul 2023 – Oct 2025",
      description: "Initiated air gun shooting sport at university, served as captain for 2 years, led team to championship at 2024 Inter-University Air Rifle Competition.",
      type: "leadership",
    },
    {
      title: "Editor",
      organization: "Hackers' Club, University of Peradeniya",
      timeframe: "Aug 2025 – Present",
      description: "Manage technical content, event coordination, and club communications for 200+ member community.",
      type: "leadership",
    },
    {
      title: "Senior Member",
      organization: "University Explorers' Club, University of Peradeniya",
      timeframe: "Jul 2024 – Present",
      description: "Organize outdoor expeditions and adventure-based leadership programs.",
      type: "leadership",
    },
    {
      title: "Programming Team Member",
      organization: "IEEE CS Student Chapter, University of Peradeniya",
      timeframe: "Jul 2024 – Nov 2025",
      description: "Organized technical workshops and coding competitions for student community.",
      type: "technical",
    },
    {
      title: "Finance Vice Chair",
      subtitle: "Central Province Organizing Committee",
      organization: "Career Compass Event, IEEE Young Professionals Sri Lanka",
      timeframe: "Apr 2025 – Sep 2025",
      description: "Managed event finances, ensuring accurate budgeting, strategic fund allocation, and post-budget analysis.",
      type: "leadership",
    },
    {
      title: "Brand Manager / OC Vice President / Team Leader",
      organization: "AIESEC in Kandy, University of Peradeniya",
      timeframe: "Feb 2022 – Nov 2024",
      description: "Led marketing campaigns and coordinated international exchange programs across cross-functional teams.",
      type: "leadership",
      expandable: true,
      details: "Managed brand identity and marketing strategy, facilitated international exchange opportunities, and led cross-functional teams to execute large-scale university events.",
    },
    {
      title: "Trainee",
      organization: "People's Bank",
      timeframe: "May 2021 – Feb 2022",
      description: "Banking operations and customer service experience.",
      type: "work",
    },
  ],

  awards: [
    {
      title: "IESL Undergraduate Inventor of the Year",
      subtitle: "Top 10 Finalist",
      project: "P-E-BO Project",
      date: "Oct 2025",
      highlight: true,
    },
    {
      title: "I-To-I / ICIIS 2025",
      subtitle: "3rd Place",
      project: "P-E-BO Project",
      date: "Nov 2025",
      highlight: true,
    },
    {
      title: "Inter-University Air Rifle Championship",
      subtitle: "Team Champion",
      project: "Air Rifle 15 shots Men's Team",
      date: "Aug 2024",
      highlight: false,
    },
    {
      title: "Magam Shooting Sports Colours Insignia",
      date: "Aug 2024",
      highlight: false,
    },
    {
      title: "Best Event Marketer",
      organization: "AIESEC in University of Peradeniya",
      date: "Feb 2024",
      highlight: false,
    },
  ],

  certifications: [
    {
      title: "AWS Technical Essentials",
      issuer: "AWS (Coursera)",
      date: "Jan 2026",
      status: "completed",
    },
    {
      title: "5G for Everyone",
      issuer: "Qualcomm (Coursera)",
      date: "Sep 2025",
      status: "completed",
    },
    {
      title: "Hands-on Linux Commands & Shell Scripting",
      issuer: "IBM (Coursera)",
      date: "May 2025",
      status: "completed",
    },
    {
      title: "Docker / Kubernetes for Beginners",
      issuer: "KodeKloud (Coursera)",
      status: "in-progress",
    },
    {
      title: "CCNA 1 & 2",
      issuer: "Cisco Networking Academy",
      status: "in-progress",
    },
    {
      title: "MoraExtreme 9.0",
      subtitle: "27th Place",
      issuer: "IEEE Student Branch, University of Moratuwa",
      date: "Oct 2024",
      status: "completed",
    },
    {
      title: "Coders V11.0",
      subtitle: "9th Place",
      issuer: "ACES, University of Peradeniya",
      date: "Oct 2024",
      status: "completed",
    },
  ],

  education: [
    {
      degree: "B.Sc. Eng. (Hons) in Computer Engineering",
      institution: "University of Peradeniya",
      timeframe: "Feb 2022 – Present",
      courses: ["Advanced Communication Networks (SDN, Docker)", "Network Security", "Databases", "Software Architecture"],
    },
    {
      degree: "CCNA (Cisco Certified Network Associate)",
      institution: "Cisco Networking Academy",
      timeframe: "Aug 2025 – Present",
      courses: ["TCP/IP", "Subnetting", "Switching", "VLANs", "Routing", "Network Security"],
    },
  ],

  contact: {
    cta: "Open to DevOps / Networking / Systems / Software Engineering internships.",
    availability: "Available for Internships",
  },

  navigation: [
    { id: "hero", label: "Home" },
    { id: "about", label: "About" },
    { id: "projects", label: "Projects" },
    { id: "skills", label: "Skills" },
    { id: "experience", label: "Experience" },
    { id: "awards", label: "Awards" },
    { id: "certifications", label: "Courses" },
    { id: "contact", label: "Contact" },
  ],
} as const;

export type Profile = typeof profile;
